shoponline.sql

This PR fixes #18 
Added 5 default products that would appear once the customer is logged in

Added default product data

---

README.md
With PHP/backend/addProduct.php
With PHP/backend/addToCart.php
With PHP/backend/adminLogin.php
With PHP/backend/cancelOrder.php
With PHP/backend/clearCart.php
With PHP/backend/customerLogin.php
With PHP/backend/databaseConnect.php
With PHP/backend/deleteProduct.php
With PHP/backend/manageDelivery.php
With PHP/backend/registerAdmin.php
With PHP/backend/registerCustomer.php

Update README and db credentials for Deployment
This PR fixes #17

Update README and db credentials for Deployment

---

.vscode/settings.json
Footer2.css
index.html

Hey! , I have added a footer that blends very well with the current theme of the website and it is also totally responsive!
Do check it out and let me.
This PR fixes #
This PR fixes #14 

Add a footer matching the current theme of the website

---

With PHP/backend/addProduct.php
With PHP/backend/addToCart.php
With PHP/backend/adminLogin.php
With PHP/backend/cancelOrder.php
With PHP/backend/clearCart.php
With PHP/backend/customerLogin.php
With PHP/backend/databaseConnect.php
With PHP/backend/deleteProduct.php
With PHP/backend/manageDelivery.php
With PHP/backend/registerAdmin.php
With PHP/backend/registerCustomer.php

This PR fixes #11 
Changed credentials to match localhost credentials

Changed credentials to match localhost credentials

---

CONTRIBUTING.md

This PR fixes #8 
This repo now has a CONTRIBUTION.md file that helps new contributors get started

Added CONTRIBUTION.md files

---

index.html

- as issue #36 says, the images in 1 row were not loading, The CDN links were broken and are replaced now with new images
This PR fixes #36 
- you can change the images if you like, I did my best to find perfect images
- also, pls merge or rebase the branch, these commits keep piling up on newer commits, it makes hard to see the changes 🥺

fix: replaced broken product cdn links

---

shoponline.sql

This PR fixes #40 
Fixed errors and removed the default data in admin table

Fixed errors in SQL file

---

.htaccess

This PR fixes #48 
Created .htaccess to route to 404.html

Created .htaccess to route to 404.html

---

installation_guidelines.md

Typo fix: installation_guidelines.md

---

README.md

feat: add issue badge

---

README.md

Added a link to CONTRIBUTING.md in the readme

---

index.html
login.html

The email id is validated for a proper format like` xxx@bbb.iiii` and if the format is not matched the user receives a warning.
This PR fixes #64 
We can achieve the above by using `pattern ` attribute in the `input` HTML tag

Email validation added

---

Footer2.css
index.html

This PR fixes #38 
what does signing my commits mean? @san-coding

Stickynav-scrollbar changes

---

Footer2.css
index.html

Reverts sudhay23/ShopOnline-Web-App#68

Revert "Stickynav-scrollbar changes"

---

index.html

Added animation on landing page

---

index.html

Added the discord link which was mistakenly removed earlier.
This PR fixes #47 

Added the discord link which was mistakenly removed earlier.

---

With PHP/backend/.env.sample
With PHP/backend/.gitignore
With PHP/backend/databaseConnect.php
composer.json
composer.lock

used vlucas/phpdotenv library to load the database credentials and other credentials at run time.
This PR fixes #6 
Tested the successful working of the environment variables manually using print statements. Attaching the screenshots below. please do check them.

used env variables to load db credentials at runtime using composer library.

---

index.html

This PR fixes #67
The display attribute of the button is set to inline flex which is actually causing this issue of pushing the button to the left end since it's parent is flex and no other elements in the column flex are flex. I over-wrote the display with inline styling, changed the display to 'block' and adding an attribute 'margin' with 0 top and auto on other sides solved the issue.

Fixed the center issue in the index.html the home page of the app.

---

README.md

<h1> Description </h1>
This PR fixes #84
Added discord and MIT License badges / sheilds to README.md

Added discord and Mit license badge #84

---

css/login.css
login.html

Added social login button on login page

---

.github/workflows/pr-greeter.yaml

added a GitHub workflow to greet the first time contributors on this repository.

---

.github/temp.txt
.github/workflows/webhost.yml

To deploy updates to website

---

.github/workflows/webhost.yml

Version2 of Deploy action
Fixes issue #96

Version2 of Deploy action

---

.github/workflows/webhost.yml
.github/workflows/webhost_pr.yml

Deploy on PR action
Addresses #96

Deploy on PR action

---

404.html

fixed 404 page

---

css/login.css
login.html

Added icon
Added shadow 
Format text

Updated new UI for Login Form

---

README.md

Added Screenshots of landing page , sign up page , login page and Footer in README.md file.
This PR fixes #63

Added latest UI Screenshots

---

admin.html
css/admin-navbar.css
css/login-navbar.css
css/navbar.css
index.html
login.html

Resolves: #90
Please let me know if it needs changes @san-coding

fix: made navbar smaller (#90)

---

css/admin-navbar.css
css/login-navbar.css
css/navbar.css

This PR fixes #134
Added hover effects for navbar buttons

fix: added hover effects to navbar
